In [1]:
pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in c:\users\김경수\appdata\roaming\python\python312\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pymysql

In [3]:
conn = pymysql.connect(host='127.0.0.1', user='root', password='1597', db='StoreData', charset='utf8')

In [4]:
cur = conn.cursor()

In [5]:
cur.execute('select * from users')

0

In [6]:
import numpy as np
import pandas as pd
import hashlib

In [7]:
for i in range(100):
    name = 'ID_' + str(i)
    pwd = np.random.randint(100)
    mail = f'user{i}@example.com'
    pwd_hash = hashlib.sha256(str(pwd).encode()).hexdigest()

    cur.execute('INSERT INTO Users (이름, 비밀번호 , email) VALUES (%s, %s, %s)', (name, pwd_hash, mail))

In [8]:
conn.commit()

In [9]:
import random

In [10]:
alpa = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
 
fee = random.sample(range(1000,2000),26)

brand = []
for i , j in zip(alpa , fee):
    brand.append([i,j])

In [11]:
for i in brand:
    cur.execute('INSERT INTO Brands (이름 , 배송비) VALUES (%s , %s)' , (i[0] , f"{i[1]:.2f}"))

In [12]:
conn.commit()

In [13]:
code = random.sample(range(1,27),26)
for i in range(74):
    code.append(random.randint(1,26))

code_fi = []
code_final = []
for i in code:
    code_fi.append(i - 1)
for i in code_fi:
    code_final.append(alpa[i])
print(code_final)

['Q', 'U', 'V', 'H', 'Z', 'T', 'F', 'O', 'R', 'N', 'A', 'I', 'M', 'D', 'S', 'K', 'X', 'L', 'W', 'P', 'Y', 'E', 'G', 'J', 'B', 'C', 'L', 'K', 'P', 'Q', 'M', 'L', 'O', 'J', 'F', 'U', 'U', 'Y', 'Q', 'N', 'F', 'O', 'Q', 'U', 'E', 'Z', 'B', 'O', 'G', 'M', 'D', 'A', 'J', 'A', 'C', 'X', 'Z', 'R', 'D', 'Z', 'R', 'H', 'O', 'R', 'A', 'Z', 'A', 'B', 'V', 'P', 'E', 'V', 'A', 'L', 'T', 'T', 'H', 'X', 'A', 'O', 'E', 'B', 'X', 'Y', 'T', 'S', 'Y', 'P', 'D', 'E', 'W', 'H', 'C', 'F', 'H', 'A', 'C', 'G', 'V', 'S']

In [14]:
dic = {'A' : 0 , 'B' : 0 , 'C' : 0 , 'D' : 0 , 'E' : 0 , 'F' : 0 , 'G' : 0 , 'H' : 0 , 'I' : 0 , 'J' : 0 , 'K' : 0 ,
       'L' : 0 , 'M' : 0 , 'N' : 0 , 'O' : 0 , 'P' : 0 , 'Q' : 0 , 'R' : 0 , 'S' : 0 , 'T' : 0 , 'U' : 0 , 'V' : 0 ,
       'W' : 0 , 'X' : 0 , 'Y' : 0 , 'Z' : 0}

result = []
for i in code_final:
    result.append(i + str(dic[i]))
    dic[i] += 1
print(result)

['Q0', 'U0', 'V0', 'H0', 'Z0', 'T0', 'F0', 'O0', 'R0', 'N0', 'A0', 'I0', 'M0', 'D0', 'S0', 'K0', 'X0', 'L0', 'W0', 'P0', 'Y0', 'E0', 'G0', 'J0', 'B0', 'C0', 'L1', 'K1', 'P1', 'Q1', 'M1', 'L2', 'O1', 'J1', 'F1', 'U1', 'U2', 'Y1', 'Q2', 'N1', 'F2', 'O2', 'Q3', 'U3', 'E1', 'Z1', 'B1', 'O3', 'G1', 'M2', 'D1', 'A1', 'J2', 'A2', 'C1', 'X1', 'Z2', 'R1', 'D2', 'Z3', 'R2', 'H1', 'O4', 'R3', 'A3', 'Z4', 'A4', 'B2', 'V1', 'P2', 'E2', 'V2', 'A5', 'L3', 'T1', 'T2', 'H2', 'X2', 'A6', 'O5', 'E3', 'B3', 'X3', 'Y2', 'T3', 'S1', 'Y3', 'P3', 'D3', 'E4', 'W1', 'H3', 'C2', 'F3', 'H4', 'A7', 'C3', 'G2', 'V3', 'S2']

In [15]:

for i in result:
    pay = random.randint(20000 , 100000)
    product = 'product_' + i
    cur.execute('INSERT INTO Products (제품코드 , 제품이름 , 고유번호 , 가격_만원) VALUES (%s , %s , %s , %s)' ,
                (i , product , alpa.index(i[0]) + 1 , f"{pay:.4f}"))

In [16]:
conn.commit()

In [17]:
num = random.sample(range(1,101),100)
size = ['SS','S','M','L','XL','XXL','Free']
for i in num:
    quantity = random.randint(0,20)
    sizes = size[random.randint(0,6)]
    cur.execute('INSERT INTO ProductOptions (제품번호 , 사이즈 , 재고수량) VALUES (%s , %s , %s)' ,
                (i , sizes , quantity))

In [18]:
conn.commit()

In [19]:

start_date='20240101'
end_date='20240818'
date_list=pd.date_range(start=start_date, end=end_date, freq='D')
print(date_list)

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10',
               ...
               '2024-08-09', '2024-08-10', '2024-08-11', '2024-08-12',
               '2024-08-13', '2024-08-14', '2024-08-15', '2024-08-16',
               '2024-08-17', '2024-08-18'],
              dtype='datetime64[ns]', length=231, freq='D')

In [20]:
number = random.sample(range(0,231),231)

In [21]:
date_list_fi = list(date_list)

In [22]:
for i in range(769):
    number.append(random.randint(0,230))

In [23]:
number

[160,
 119,
 122,
 134,
 85,
 215,
 30,
 3,
 222,
 45,
 228,
 204,
 184,
 138,
 142,
 162,
 109,
 25,
 131,
 154,
 126,
 221,
 121,
 197,
 218,
 9,
 28,
 4,
 224,
 183,
 145,
 66,
 80,
 15,
 205,
 103,
 90,
 40,
 64,
 52,
 211,
 34,
 83,
 22,
 14,
 210,
 53,
 21,
 128,
 20,
 41,
 201,
 65,
 55,
 12,
 129,
 163,
 29,
 50,
 89,
 71,
 56,
 196,
 229,
 171,
 7,
 68,
 18,
 185,
 174,
 152,
 217,
 107,
 43,
 79,
 139,
 57,
 178,
 157,
 48,
 82,
 227,
 44,
 169,
 115,
 179,
 151,
 8,
 186,
 59,
 11,
 39,
 16,
 192,
 13,
 223,
 149,
 206,
 170,
 164,
 63,
 155,
 176,
 165,
 78,
 27,
 189,
 133,
 69,
 72,
 116,
 214,
 190,
 118,
 230,
 35,
 104,
 108,
 168,
 173,
 61,
 137,
 93,
 226,
 220,
 58,
 1,
 191,
 70,
 219,
 38,
 95,
 199,
 112,
 114,
 31,
 202,
 193,
 36,
 97,
 117,
 54,
 87,
 73,
 0,
 5,
 32,
 143,
 24,
 88,
 172,
 194,
 120,
 47,
 19,
 175,
 161,
 81,
 200,
 212,
 123,
 62,
 23,
 33,
 74,
 141,
 153,
 125,
 26,
 195,
 51,
 150,
 166,
 96,
 140,
 187,
 76,
 101,
 132,
 92,
 130,
 213,
 181,
 158,
 100,
 177,
 188,
 75,
 42,
 10,
 105,
 216,
 135,
 67,
 86,
 17,
 127,
 156,
 77,
 37,
 208,
 102,
 84,
 113,
 99,
 98,
 203,
 111,
 60,
 159,
 180,
 46,
 106,
 148,
 198,
 6,
 146,
 182,
 209,
 124,
 167,
 144,
 225,
 147,
 110,
 136,
 49,
 91,
 207,
 94,
 2,
 47,
 20,
 211,
 51,
 66,
 227,
 125,
 54,
 161,
 47,
 211,
 227,
 155,
 141,
 230,
 105,
 43,
 193,
 18,
 179,
 43,
 221,
 50,
 52,
 169,
 42,
 94,
 40,
 94,
 37,
 215,
 57,
 80,
 53,
 205,
 123,
 18,
 159,
 204,
 66,
 77,
 125,
 80,
 121,
 1,
 53,
 66,
 123,
 179,
 62,
 137,
 73,
 79,
 77,
 77,
 212,
 13,
 142,
 164,
 229,
 223,
 126,
 29,
 45,
 202,
 115,
 109,
 51,
 190,
 147,
 203,
 160,
 124,
 119,
 7,
 99,
 211,
 64,
 46,
 121,
 20,
 108,
 89,
 145,
 138,
 179,
 190,
 139,
 205,
 141,
 119,
 47,
 14,
 66,
 1,
 102,
 161,
 167,
 122,
 221,
 155,
 30,
 209,
 2,
 66,
 101,
 4,
 221,
 182,
 65,
 18,
 223,
 10,
 138,
 136,
 116,
 69,
 193,
 96,
 83,
 150,
 184,
 112,
 104,
 35,
 75,
 56,
 21,
 62,
 75,
 34,
 220,
 14,
 78,
 39,
 18,
 177,
 128,
 143,
 166,
 39,
 127,
 220,
 20,
 81,
 212,
 178,
 140,
 198,
 222,
 30,
 177,
 106,
 19,
 133,
 155,
 113,
 189,
 116,
 224,
 212,
 129,
 162,
 78,
 11,
 8,
 58,
 83,
 125,
 133,
 35,
 146,
 82,
 49,
 131,
 56,
 122,
 107,
 143,
 18,
 12,
 108,
 156,
 125,
 159,
 93,
 146,
 206,
 33,
 210,
 93,
 82,
 212,
 214,
 152,
 53,
 31,
 48,
 99,
 174,
 83,
 132,
 15,
 184,
 181,
 213,
 79,
 87,
 85,
 213,
 174,
 111,
 13,
 20,
 13,
 175,
 24,
 210,
 197,
 62,
 35,
 138,
 212,
 201,
 33,
 150,
 159,
 158,
 82,
 48,
 101,
 202,
 163,
 146,
 3,
 190,
 229,
 81,
 163,
 147,
 9,
 80,
 29,
 34,
 221,
 10,
 4,
 158,
 214,
 49,
 63,
 12,
 186,
 48,
 61,
 18,
 110,
 86,
 183,
 93,
 75,
 41,
 202,
 179,
 205,
 162,
 129,
 73,
 33,
 160,
 108,
 75,
 31,
 159,
 214,
 97,
 19,
 59,
 173,
 191,
 162,
 190,
 88,
 154,
 78,
 19,
 189,
 140,
 133,
 85,
 6,
 174,
 68,
 29,
 106,
 215,
 152,
 160,
 74,
 207,
 212,
 63,
 124,
 63,
 59,
 87,
 88,
 10,
 146,
 118,
 70,
 213,
 64,
 178,
 115,
 39,
 170,
 21,
 11,
 167,
 13,
 4,
 106,
 175,
 9,
 179,
 89,
 141,
 169,
 200,
 97,
 155,
 198,
 91,
 205,
 0,
 37,
 113,
 150,
 141,
 26,
 220,
 137,
 167,
 143,
 119,
 70,
 139,
 143,
 86,
 107,
 115,
 41,
 34,
 218,
 152,
 180,
 187,
 39,
 154,
 59,
 21,
 87,
 31,
 35,
 18,
 106,
 73,
 9,
 125,
 41,
 26,
 167,
 12,
 38,
 62,
 115,
 53,
 174,
 228,
 149,
 156,
 2,
 129,
 171,
 204,
 229,
 56,
 173,
 139,
 113,
 47,
 53,
 158,
 106,
 91,
 229,
 68,
 132,
 207,
 141,
 72,
 165,
 101,
 23,
 114,
 17,
 33,
 53,
 146,
 161,
 105,
 26,
 224,
 64,
 196,
 129,
 145,
 4,
 61,
 165,
 185,
 107,
 61,
 187,
 20,
 117,
 146,
 7,
 95,
 40,
 66,
 192,
 226,
 54,
 156,
 17,
 115,
 19,
 136,
 191,
 96,
 142,
 219,
 200,
 25,
 192,
 40,
 178,
 17,
 66,
 103,
 134,
 224,
 198,
 91,
 99,
 71,
 193,
 144,
 143,
 135,
 150,
 203,
 207,
 60,
 189,
 70,
 22,
 71,
 79,
 226,
 176,
 223,
 4,
 7,
 146,
 71,
 206,
 51,
 147,
 75,
 175,
 214,
 161,
 134,
 35,
 45,
 170,
 192,
 14,
 48,
 160,
 1,
 79,
 61,
 61,
 18,
 23,
 74,
 167,
 160,
 144,
 53,
 119,
 112,
 77,
 140,
 66,
 102,
 204,
 99,
 128,
 96,
 53,
 189,
 65,
 122,
 19,
 94,
 148,
 184,
 75,
 159,
 213,
 134,
 150,
 145,
 167,
 194,
 127,
 167,
 150,
 116,
 54,
 118,
 88,
 173,
 145,
 213,
 150,
 227,
 146,
 154,
 140,
 99,
 123,
 143,
 103,
 111,
 171,
 193,
 17,
 173,
 143,
 138,
 202,
 196,
 65,
 111,
 219,
 81,
 191,
 210,
 35,
 35,
 118,
 223,
 138,
 161,
 13,
 177,
 129,
 200,
 108,
 114,
 77,
 97,
 23,
 207,
 190,
 158,
 69,
 102,
 178,
 87,
 44,
 63,
 166,
 70,
 223,
 118,
 198,
 50,
 109,
 68,
 219,
 16,
 160,
 113,
 36,
 223,
 115,
 208,
 40,
 33,
 90,
 115,
 187,
 219,
 0,
 226,
 19,
 215,
 145,
 4,
 3,
 130,
 152,
 217,
 79,
 85,
 160,
 127,
 31,
 133,
 151,
 204,
 195,
 197,
 137,
 149,
 229,
 124,
 82,
 29,
 229,
 0,
 227,
 107,
 152,
 66,
 46,
 97,
 89,
 229,
 187,
 12,
 30,
 39,
 37,
 119,
 31,
 13,
 77,
 122,
 140,
 11,
 54,
 93,
 103,
 44,
 125,
 104,
 106,
 156,
 83,
 157,
 166,
 3,
 51,
 71,
 190,
 102,
 198,
 47,
 203,
 0,
 49,
 103,
 200,
 211,
 123,
 222,
 58,
 0,
 221,
 88,
 113,
 55,
 13,
 131,
 149,
 15,
 172,
 131,
 217,
 206,
 181,
 189,
 218,
 228,
 213,
 174,
 90,
 91,
 180,
 15,
 60,
 223,
 56,
 58,
 136,
 209,
 103,
 88,
 103,
 4,
 93,
 217,
 14,
 228,
 30,
 139,
 7,
 161,
 43,
 114,
 129,
 116,
 73,
 138,
 35,
 50,
 165,
 175,
 45,
 31,
 153,
 163,
 92,
 1,
 222,
 151,
 1,
 82,
 117,
 230,
 37,
 181,
 205,
 82,
 38,
 229,
 121,
 3,
 129,
 203,
 62,
 35,
 71,
 148,
 156,
 192,
 200,
 117,
 212,
 224,
 50]

In [24]:
np.max(number)

230

In [25]:
date_list_final = []
for i in number:
    date_list_final.append(date_list_fi[i])

In [26]:
date_list_final = np.sort(date_list_final)

In [27]:
id = []
for i in range(100):
    id.append('id_' + str(i))

In [28]:
status = ['Pending' , 'SHIPPED']

In [29]:
for i in date_list_final:
    User_id = random.randint(0,99)
    ST = random.randint(0,1)
    price = random.randint(0 , 100000)
    fee = random.randint(0 , 30000)
    cur.execute('INSERT INTO Orders (유저ID , 주문날짜 , 배송지주소 , 배송현황 , 할인가격 , 배송비) VALUES (%s , %s , %s , %s , %s , %s)' , 
                (id[User_id] , i , '----' , status[ST] , f"{price:.2f}" , f"{fee:.2f}"))

In [30]:
conn.commit()

In [31]:
su = [1,2,3,4,5]

In [32]:
nu = []
for i in range(1,1001):
    nu.append(i)

In [33]:
op = np.arange(1,101)

In [34]:
for i in range(2000):
    nu.append(random.randint(1,1000))

In [35]:
len(nu)

3000

In [36]:
nu = np.sort(nu)

In [37]:
for i in nu:
    op_num = random.randint(0,99)
    su_num = random.randint(0,4)
    cur.execute('INSERT INTO OrderItems (주문번호 , 옵션번호 , 수량) VALUES (%s , %s , %s)' ,
                (i , op[op_num] , su[su_num]))

In [38]:
conn.commit()

In [39]:
conn.close()